# Capistrano is a framework for building automated deployment scripts.
gem 'capistrano', '>= 3.6.1'
gem 'capistrano-rbenv', '~> 2.0'
gem 'capistrano-yarn'
gem 'capistrano-bundler', '~> 1.1.2'
gem 'capistrano-rails', '~> 1.0'
gem 'caxlsx', '~> 3.0'
gem 'axlsx_rails'
